---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    mongo-root-password: AgCn+qAw/0vWE83nYS3W4Lv3+WWu/qLRoraH/wLC93gnESQyvB/6ZOFP2o6lnPpfFCLGJx+L0iTj/iMcvCGYgD8IvrBv5tJJn6fZ6DC5Zkrh9iW95iQCFGbwJS/gnSU2uBY5ZQnaSXw83nhJP6KXFLIfmpEBiDhoUzro1xmVIKgHoRQNjkrxhQ01ze7tpl/ju/H+f5n+RJ79VV/ter2ph9QiTovh85QDO2Pvf5tpGf8+6SJmfWXwwEi8saLEiJKHiZ1/XKj9VBSeBtWk+DKqnE1Lyyu6OC8OmvHngR6cUqgZObt/CN7PqcPF9tTsqati5s1TqLccG8aqW9NTvsmNahZ7Pn4+z5Py/+6AipmBEgtktV9yYMKmhA1rh47lnrso49GhxraaJWf4tTLrtvM7jBWlbSBNYnV8TJIGFFGXqsGCC7X4ySJXl9i1VrTcbPz6Ojqcn3N7IvrexbFDsAIryRcttszVSejdOgknE0sJC1IB9YaA51G+MCENpr0JQhlcnVQ4Uz25oSihSQxRrDp6eDXvXNzvKPJlLehXw0iESxUXkhIsZJELYq/38g7t9HZ6V+Hy+WSonpAVdAyvPuN6pv1PD1xHSUduvihlXAqyjBbwgB0oFYSi1OdzhJImfDPee8A1vEhjuHoSt5CeURWyP1tlmReU+88jpKQjsD3xAVADpyeX0IvbPzM+JfOUUouGwoF1SvwxBR15VseNzrsvwA==
    mongo-root-username: AgB83kpPxgem/6db9nBNTIy8Q+/RBidcPWHj3yB+czNOyj7M+rIdTDUlqnXlF86InXLvMKv147LBAFIIW6LJheeMKQlUscUMoHTXKLKt3KZmECkxtyCsT/1clGjwV+1PmEHecF4zCXKu2F/ZyvFnjKWWntDut4okcwCQfJEXUYloctTuuBEeZ81Of6rIfcs5wJ8JPqPouIKx+H4cKc25kcGJQKJhIyzFHOfRZCdbARYh+Y21XF8bdaHQME/7QBSWSKPiZaJMFU/zcCqMZuLTAUXj7NnA9LvTUUkWaC54M3fljpLhtoBZwle6MqYz1efh3YO02uxIsrLl8k6kD9YeKsDIhnedwqp6TeYpuTMfAREJR75LSOkAAlgMC3wewkBAOyn1l5gO74GuFzgIFw+22BDLHXluIHC+m/panHAWvPyspAlAfTpi/VXVhpSRsE0yLVRcM7lX8XlOsRwK2iWkOf4ML10l0cox2RblkyDhhII0H8XVQQdbqZugR6/n6ZANLMVjvbp4v3lKKiWGXPQF24KGH3ltT5EzPIl+hlau3oJca9Kp5+/76v1SzZYUp5FLIXPihNIHpSSe1cIUJcdd4XOp43/tNQju2qMq6cO61EU6RKcrRw996etpw2O1rCWWu6VJC9bY/NlgekSnCCABDmN7cXsgKtqPTieXOzv8+m9ifPigGtjBNTRqVzJjVFAW5zkp9gDpOQ==
    mongo-uri: AgAhttXv8Qlcck3zhq/fhLbQ4EZH9s96Fgn1OCWQDB4sJ41EzoVY9s/X6CyzZp3DIcS9W5ps/Nyoac0/zJPVV2ImZcwpOofIAF9JRkCelgGTeaeVHV/ttzmZArvinh16HoILRJQb0BpM+p2ZZjXZQFu6uKfysFSaXtCJPGQtcswon4X2iitMbYm9byqa0MnbsTvJGKSJMRYfRkA4krDnJuS2iyphh6qDGPH9Rn+O05IEHOP9l1yVbwPGutHnelLgTaVA+7Zb7QLF4MV+/KiJVljFjTFWC5C0d6nc2ru7Lld4DyK4It52ApjScbfLAVKvK7ejG2QG0NzVtltJcm/c7XG0k3eq1ZEfu/QU0DIneJ2OQOugf5hoSt0ajr1FUJqSt11UzQXc9cwnqHMyFapdMQDBSLYUcIlZtYvQuYaV6xLRRGT6e0azcBwLgTfJul7+7cLUWmrhc6afrWznTj6wSyTVh6Wgw4DZFENQq/+crq600g5ZsZK18rOPJA2l6lHNzmok9z5ehvOq2Rj9My59lvlkYevUm5mVdPzoZ1T9+snE4CqPbEWj0k3UynnA7Bf3TRmiaAqEPKnMJdtLfgGJaHKnPGyPrc6pBSrHJSd0/l3I+l0S3An/mNf6a9k5Rqk0myoAGEXmnOLt9Wib2sJxb8PaKTkwcgR3r1fjAATMIhTnqQgSDU4Rv4goIaA503lPtyxwdvsFnSSwIwa35C/hk7INzUUzTIn8TjvdW2j69y8y+KTGyy1Y1/EyVo5QYKVNCpp4PlZ2eeOBCSNaAbSbpw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Opaque
