apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-vault-secret
  namespace: default
spec:
  refreshInterval: "1h" # Automatically syncs secrets from Vault every hour
  secretStoreRef:
    name: vault-backend-store
    kind: ClusterSecretStore
  target:
    name: mongodb-secret # The target Kubernetes Secret object created in 'default' namespace
    creationPolicy: Owner
  data:
    - secretKey: mongo-root-username # Key name inside target Kubernetes Secret
      remoteRef:
        key: secret/data/mongodb # Path in HashiCorp Vault KV-v2 engine
        property: MONGO_USER
    - secretKey: mongo-root-password # Key name inside target Kubernetes Secret
      remoteRef:
        key: secret/data/mongodb # Path in HashiCorp Vault KV-v2 engine
        property: MONGO_PASS